DESIGN_DOCUMENT = {
    "overview": {
        "title": "거짓의 방",
        "genre": "2D 횡스크롤 액션 플랫포머",
        "core": [
            "SANABI의 공중 이동 감각",
            "마리오식 레벨 문법",
            "Have a Nice Death의 패턴 학습형 전투",
        ],
        "tone": "어둡고 철학적 + 연출 과장",
        "keywords": ["거짓", "기억", "자기기만", "선택"],
    },
    "world": {
        "concept": "주인공이 외면한 기억과 거짓말이 물리 공간으로 구현된 장소",
        "escape_condition": "진실을 직면하면 탈출 가능",
        "protagonist": [
            "과거의 중대한 선택을 숨김",
            "기억이 조각나 있으며 신뢰할 수 없음",
            "모든 보스는 주인공이 만든 자기기만의 형상",
        ],
    },
    "stages": [
        {
            "name": "부정의 복도",
            "symbol": "부정",
            "grappling": "수평 간격 6~8타일, 점프만으로도 도달 가능한 거리에서 시작",
            "air_route": "낮은 높이 공중 발판 3개 연속 배치",
            "hazard": "가벼운 낙사 구간(2~3타일)",
            "mario_flow": [
                "안전 발판 3개",
                "낙사 구간 + 적 1마리",
                "낙사+적+이동 플랫폼 조합",
            ],
        },
        {
            "name": "회피의 극장",
            "symbol": "회피",
            "grappling": "바닥 2~3타일 높이, 공중 대시 없으면 도달 어려움",
            "air_route": "그래플링 후 공중 대시 1회 필수",
            "hazard": "하강 낙사 + 적 순찰",
            "gimmick": "진실을 알면 나타나는 발판 (표지판 읽기 후 5초간 생성)",
        },
        {
            "name": "합리화의 기계실",
            "symbol": "합리화",
            "grappling": "지그재그 배치, 이동 자체가 퍼즐",
            "air_route": "떨어지는 플랫폼 회피하며 이동 유지",
            "hazard": "압사형 움직이는 벽",
            "gimmick": "스토리 아이템 보유 시만 보이는 길",
        },
        {
            "name": "왜곡의 환상도시",
            "symbol": "왜곡",
            "grappling": "기울어진 벽 포인트 + 수직 상승",
            "air_route": "수직 상승 후 공중 전투 강제",
            "hazard": "화면 좌우 반전 3초",
            "gimmick": "중력 반전 구간 (5초 유지 → 착지로 해제)",
        },
        {
            "name": "망각의 심연",
            "symbol": "망각",
            "grappling": "불규칙 간격, 실패 시 큰 낙사 패널티",
            "air_route": "공중 이동 + 적 2종 혼합 전투",
            "hazard": "시간 제한 플랫폼",
            "gimmick": "시간 정지 구간 (스토리 아이템 보유 시만 가능)",
        },
    ],
    "monsters": [
        {
            "name": "거짓의 잔영",
            "symbol": "부정",
            "hp": 1,
            "move": "순찰 (좌우 3~5타일)",
            "attack": "접촉 데미지",
            "pressure": "낙사 직전 배치",
            "animations": {
                "idle": "8프레임",
                "walk": "10fps 6프레임",
                "chase": "12fps 8프레임",
                "hit": "4프레임",
                "death": "6프레임 + 먼지",
            },
        },
        {
            "name": "회피의 사도",
            "symbol": "회피",
            "hp": 1,
            "move": "돌진 준비 후 단거리 돌진",
            "attack": "정지 0.5초 → 파란빛 0.3초 → 돌진 0.35초",
            "pressure": "좁은 플랫폼에서 회피 유도",
            "animations": {
                "idle": "6프레임",
                "chase": "8프레임(예열)",
                "attack": "6프레임",
                "hit": "4프레임",
                "death": "6프레임",
            },
        },
    ],
    "bosses": [
        {
            "name": "부정의 감독",
            "symbol": "부정",
            "appearance": "마스크 감독 + 카메라 렌즈",
            "phases": [
                "Phase 1: 직선 카메라 빔",
                "Phase 2: 빔 + 조명 낙하",
                "Phase 3: 빔 + 조명 + 공중 추적",
            ],
            "patterns": [
                {
                    "name": "카메라 빔",
                    "telegraph": "바닥 붉은 직선 0.4초",
                    "attack": "0.3초 레이저",
                    "evade": "점프/대시",
                },
                {
                    "name": "조명 낙하",
                    "telegraph": "원형 표시 0.5초",
                    "attack": "낙하 + 폭발",
                    "evade": "이동",
                },
                {
                    "name": "컷 지시(페이크)",
                    "telegraph": "손짓 “컷!”",
                    "attack": "입력 반응 0.1초 지연",
                    "evade": "미리 점프/대시",
                },
            ],
            "cutscenes": {
                "intro": "커튼 오픈 + 카메라 플래시",
                "phase_change": "렌즈 파열 연출",
                "death": "렌즈 완전 깨짐",
            },
        },
        {
            "name": "회피의 무용수",
            "symbol": "회피",
            "appearance": "검은 리본 + 하얀 가면",
            "patterns": [
                {
                    "name": "리본 베기",
                    "telegraph": "0.3초",
                    "attack": "부채꼴 베기",
                    "evade": "수평 대시",
                },
                {
                    "name": "하강 찌르기",
                    "telegraph": "공중 점프",
                    "attack": "직하강 찌르기",
                    "evade": "좌우 이동",
                },
                {
                    "name": "잔상 페이크",
                    "telegraph": "허상 1회",
                    "attack": "0.2초 뒤 진짜 공격",
                    "evade": "허상 타이밍 대시 금지",
                },
            ],
        },
        {
            "name": "합리화의 판사",
            "symbol": "합리화",
            "appearance": "거대한 망치 + 저울",
            "patterns": [
                {
                    "name": "망치 낙하",
                    "telegraph": "0.6초",
                    "attack": "바닥 폭발 범위",
                    "evade": "타이밍 점프",
                },
                {
                    "name": "저울 판결",
                    "telegraph": "좌/우 판결 표시",
                    "attack": "한쪽만 안전",
                    "evade": "올바른 쪽 이동",
                },
                {
                    "name": "판결 선언(장판)",
                    "telegraph": "안전 구역 축소",
                    "attack": "지속 피해 장판",
                    "evade": "공중 이동",
                },
            ],
        },
        {
            "name": "왜곡의 광대",
            "symbol": "왜곡",
            "appearance": "좌우 반전된 얼굴",
            "patterns": [
                {
                    "name": "화면 반전 돌진",
                    "telegraph": "3초 좌우 반전",
                    "attack": "직선 돌진",
                    "evade": "반전 시점 대시",
                },
                {
                    "name": "분신 소환",
                    "telegraph": "분신 2개",
                    "attack": "하나만 실제 공격",
                    "evade": "패턴 관찰",
                },
                {
                    "name": "와이어 필수 회피",
                    "telegraph": "바닥 전체 경고",
                    "attack": "바닥 전체 타격",
                    "evade": "그래플링 필수",
                },
            ],
        },
        {
            "name": "망각의 기록자",
            "symbol": "망각",
            "appearance": "책장으로 된 거대 괴물",
            "patterns": [
                {
                    "name": "페이지 폭풍",
                    "telegraph": "원거리 발사",
                    "attack": "다발 투사체",
                    "evade": "플랫폼 이동",
                },
                {
                    "name": "책장 벽 압박",
                    "telegraph": "좌우 벽 접근",
                    "attack": "공간 압축",
                    "evade": "중앙 이동 후 대시",
                },
                {
                    "name": "시간 정지 구간",
                    "telegraph": "시간 정지 시작",
                    "attack": "발판만 이동",
                    "evade": "타이밍 점프",
                },
            ],
        },
    ],
    "items": [
        {
            "name": "기억의 파편",
            "type": "패시브",
            "effect": "최대 HP +1",
            "meaning": "잊힌 기억의 조각",
            "location": "STAGE 2 숨겨진 길",
            "reason": "“진실을 보면 길이 보인다” 연출",
        },
        {
            "name": "거짓의 열쇠",
            "type": "액티브",
            "effect": "특정 문 개방",
            "meaning": "스스로 만든 거짓을 깨는 도구",
            "location": "STAGE 3 기계실 끝",
            "reason": "보스 전 전개 연결",
        },
        {
            "name": "붉은 리본",
            "type": "스토리",
            "effect": "STAGE 4 숨겨진 발판 표시",
            "meaning": "회피했던 감정의 실체",
            "location": "STAGE 4 초입",
            "reason": "왜곡 구간 안내",
        },
    ],
    "presentation": {
        "hitstop": "0.05초",
        "shake": {"low": "2px", "mid": "4px", "high": "6px"},
        "slowmo": "보스 페이즈 전환 0.3초",
        "emotion": "HP 30% 이하 시 공격 템포 +15%",
    },
}
