PLAYER_RUN_FRAMES = 6
PLAYER_RUN_FRAME_SIZE = (32, 32)
PLAYER_IDLE_FRAMES = 1
PLAYER_IDLE_FRAME_SIZE = (32, 32)
PLAYER_RUN_FILE = "player.png"
PLAYER_IDLE_FILE = "player.png"

ENEMY1_FRAMES = 4
ENEMY1_FRAME_SIZE = (16, 16)
ENEMY1_FILE = "enemy1.png"

ENEMY2_FRAMES = 4
ENEMY2_FRAME_SIZE = (16, 16)
ENEMY2_FILE = "enemy2.png"

BOSS_ACTIVATION_DISTANCE = 220
